<?php


/**
 * 
 * This module is used for managing banners.
 *
 */



/**
 * Implements hook_permission().
 *
 * We need some standard entry points so we can have consistent urls for
 * different Object actions
 */


function fossee_site_banner_permission(){
	return array(
		"create new_banner" => array(
			"title" => t("Create new banner"),
			"description" => t("Allow users to create new banners"),
		),
		"see available banners" => array(
			"title" => t("See Available Banners"),
			"description" => t("User can see all available banners"),
		),
		"set banner status" => array(
			"title" => t("Set Banner Status"),
			"description" => t("Allows users to set Banner Active/Inactive"),
		),
		"set allowed sites" => array(
			"title" => t("Set Allowed Sites"),
			"description" => t("Allows user to set the sites in which banner can be displayed"),
		),
    "add website" => array(
      "title" => t("Add Website"),
      "description" => t("Allow user to add new websites to the fossee_website_index table"),
    ),
    "delete banner" => array(
      "title" => t("Delete Banner"),
      "description" => t("Allows user to delete banners permanently"),
    ),
    "delete website" => array(
      "title" => t("Delete Website"),
      "description" => t("Allows user to delete websites from the list of available websites"),
    ),
    "administer banners" => array(
      "title" => t("Administer Banners"),
      "description" => t("Allows users to manage settings like banner file size, extensions etc")
    )
	);
}


/**
 * Implements hook_menu().
 *
 * We need some standard entry points so we can have consistent urls for
 * different Object actions
 */

function fossee_site_banner_menu() {
	$items = array();

	$items['fossee-site-banner/new-banner'] = array( // used to create new banners
		'title' => 'New Banner',
		'description' => 'Create New Banner.',
		'page callback' => 'drupal_get_form',
		'page arguments' => array('new_banner_form'),
		'access arguments' => array("create new_banner"),
		'file' => 'inc/new_banner.inc',
	);

	$items['fossee-site-banner/edit-banner'] = array( // used to create new banners
		'title' => 'Edit Banner',
		'description' => 'Edit the banner details.',
		'page callback' => 'drupal_get_form',
		'page arguments' => array('new_edit_banner_form',2),
		'access arguments' => array("create new_banner"),
		'file' => 'inc/edit_banner.inc',
	);

	$items['fossee-site-banner/banners'] = array( // shows all available banners and if they are active/inactive
		'title' => 'Available Banners',
		'description' => 'The Banners Available.',
		'page callback' => 'fossee_site_banner_banners',
		'page arguments' => array(1),
		'access arguments' => array('see available banners'),
		'file' => 'inc/all_banners.inc',
	);


	$items['fossee-site-banner/set-banner-active/%'] = array( // receives ajax call to set a banner active with an argument containing the id of the banner
		'page callback' => 'set_banner_active',
		'type' => MENU_CALLBACK,
		'access arguments' => array('set banner status'),
		'page arguments' => array(2),
		'file' => 'inc/set_banner_status.inc',
	);


	$items['fossee-site-banner/set-banner-inactive/%'] = array( // receives ajax call to set a banner inactive with an argument containing the id of the banner
		'page callback' => 'set_banner_inactive',
		'type' => MENU_CALLBACK,
		'access arguments' => array('set banner status'),
		'page arguments' => array(2),
		'file' => 'inc/set_banner_status.inc',
	);


	$items['fossee-site-banner/banner-settings/%'] = array( // used to change settings like the sites where the banner will be displayed
		'title' => 'Banner Settings',
		'description' => 'Create New Banner.',
		'page callback' => 'drupal_get_form',
		'page arguments' => array('banner_settings_form',2),
		'access arguments' => array('set allowed sites'),
		'file' => 'inc/banner_settings.inc',
	);

  $items['fossee-site-banner/add-website'] = array( // used to add new websites to the list of sites where banner will be displayed
    'title' => 'Add Websites',
    'description' => 'Add new website.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array(
      'add_website_form',
    ),
    'access arguments' => array('add website'),
    'file' => 'inc/add_website.inc',
  );

  $items['fossee-site-banner/delete-banner/%'] = array( // receives ajax call to set a banner active with an argument containing the id of the banner
    'page callback' => 'delete_banner',
    'type' => MENU_CALLBACK,
    'access arguments' => array('delete banner'),
    'page arguments' => array(2),
    'file' => 'inc/delete_banner.inc',
  );

  $items['fossee-site-banner/delete-website/%'] = array( // receives ajax call to set a banner active with an argument containing the id of the banner
    'page callback' => 'delete_website',
    'type' => MENU_CALLBACK,
    'access arguments' => array('delete website'),
    'page arguments' => array(2),
    'file' => 'inc/delete_website.inc',
	);
	
	$items['fossee-site-banner/edit-website/%'] = array( // receives ajax call to set a banner active with an argument containing the id of the banner
    'page callback' => 'drupal_get_form',
    'type' => MENU_CALLBACK,
    'access arguments' => array('delete website'),
    'page arguments' => array('edit_website_form',2),
    'file' => 'inc/edit_website.inc',
  );

  /* ADMIN SETTINGS */
  //For mentioning extension allowed for image and pdf
  $items['admin/settings/banners'] = array(
    'title' => 'Banner Settings',
    'description' => 'Banner Settings',
    'page callback' => 'drupal_get_form',
    'page arguments' => array(
      'banner_settings_form'
    ),
    'access arguments' => array(
      'administer banners'
    ),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'settings.inc'
  );

  return $items;
}


function fossee_site_banner_cron(){

  module_load_include('inc','fossee_site_banner','inc/mail');
  $domain_name = "http://".$_SERVER['SERVER_NAME'] . base_path();

  $time_range = 70*24*60*60;
  $result = db_select('fossee_banner_details','n')
    ->fields('n',array('id','file_name','status','banner_name'))
    //->range(0,20)
    //->condition(db_or()->condition('n.created_timestamp',time()-$recent_time,'>')->condition('n.last_updated',time()-$recent_time))
    ->condition('n.timestamp',time()+$time_range,"<")
    ->execute(); // returns the banners from the fossee_banner_details table

  foreach ($result as $res){
    $banner_link = $domain_name."fossee-site-banner/banner-settings/".$res->id;
    $params['banners'] .= t('<br><a href="'.$banner_link.'">'.$res->banner_name.'</a>');
  }

  $params['to'] = variable_get('fossee_site_banner_banner_admin',NULL);
  drupal_mail('fossee_site_banner','banner_validity_reminder',$params['to'],language_default(),$params);

}




